### ISSUE TITLE
Enhancement: Code Analysis Function

### ISSUE THREAD

**Issue by TobyLobster** [ZornsLemma/py8dis#12]
Code analysis can help to label various cases:

    ; case 1
    LDA #2              ; replace with a known sprite constant!
    JSR draw_sprite

    ; case 2
    LDA #$17            ; replace with a known room constant!
    STA current_room_number

    ; case 3
    LDA #5              ; replace with a known CRTC constant!
    STA crtc_address_register

To handle all these cases, add a function (this gets a little bit sketchy) like:

    substitute_constantA("JSR", "draw_sprite", sprite_constant_dict)

Basically this looks for a "JSR draw_sprite" instruction, and if the value of A is known at this point (via cpu state) then replace the `LDA #` literal value where A was set with a name from the given constants dictionary.

e.g. It should find and fix this case:

    LDA #<constant>
    LDX ...
    LDY ...
    JSR draw_sprite

Similarly for the other examples:

    substitute_constantA("STA", "current_room_number", room_constant_dict)
    substitute_constantA("STA", "crtc_address_register", crtc_registers_enum)

Note that here we are looking specifically for `STA current_room_number`, but not `STA current_room_number,Y` so we need to specify a specific opcode I guess - that seems slightly more messy than I'd ideally like.

This might take a little work to implement :-) but it's a nice feature.

**Comment by ZornsLemma** [comment]
This is a good idea. I can't think of a really nice way to specify specific opcodes - perhaps the first argument could be a mnemonic or a list of opcodes and we'd have some sort of helper function/constant which can "hide" the raw opcode hex.

Just for the record (and as you probably already know), the "core" of this functionality already exists in acorn.py's acorn_argument_finder_hook; it would "just" need pulling out and generalising a bit.

**Comment by TobyLobster** [comment]
I had a thought: I'm thinking we could mark which of the opcodes have no ornaments i.e. LDA addr without any brackets or ,X or ,Y. Then we only need to match against those opcodes.

Thanks for the reminder. I'll take a look.

**Comment by TobyLobster** [comment]
I'm tempted even to have the parameter as the full instruction "STA sprite_number" and use some regexes to calculate the addressing mode, extract the mnemonic and the address label. Mnemonic+addressing mode gives the opcode.

**Comment by ZornsLemma** [comment]
The regex idea sounds quite cool, although I do wonder if matching the addressing mode against the opcode table in cpu6502.py is going to be a bit fiddly - it might be OK though.

**Comment by TobyLobster** [comment]
Implemented.
