### ISSUE TITLE
Auto-generate inline comments when constant substitution has no immediate values available

### ISSUE THREAD

**Issue by ZornsLemma** [ZornsLemma/py8dis#18]
Constant substitution can replace things like "LDA #5:JSR plot_sprite" with "LDA #sprite_foo:JSR plot_sprite", but this doesn't work if we have "LDA room_data:JSR plot_sprite" as there's no immediate constant to replace with a named constant. However, we could still generate an inline comment to show that A is the sprite number, e.g.

    LDA room_data              ; A=sprite number
    LDX room_data+1            ; X=x-coordinate
    LDY room_data+2            ; Y=y-coordinate
    JSR plot_sprite

The CPU state would need to track the last instruction that changed each register in order to implement this.

_Originally posted by @TobyLobster in https://github.com/ZornsLemma/py8dis/issues/17#issuecomment-1193382396_

**Comment by TobyLobster** [comment]
Perhaps this feature is really about describing a subroutine. With this information, a subroutine comment can be output also:
```
; Plot Sprite
;
; On Entry:
;     A=sprite number
;     X=x-coordinate
;     Y=y-coordinate
plot_sprite
    ...
```

**Comment by TobyLobster** [comment]
I could imagine a routine:

`subroutine(addr, label, title, description, entry_a, entry_x, entry_y, exit_a, exit_x, exit_y)`

It would fill in a complete subroutine header comment with title, description, and optional 'on entry', and 'on exit' sections , allowing both entry and exit values to be commented when used, e.g.

```
lda room_data               ; A=sprite number
jsr get_sprite_info
cpy #9                      ; Y=sprite height in pixels
bcs tall_sprite
```

**Comment by ZornsLemma** [comment]
This is a nifty idea. I appreciate you're just sketching out an API here and I'm half repeating stuff we've already discussed, but the one thing this seems to miss is a way to do the "convert arguments to constants" stuff we do for Acorn OS hooks.

I don't think (but I'd be happy to be proved wrong) a dictionary would really be ideal here, because for subroutine 1 you might need to look at A first, then interpret X in the context of a specific A value, while for subroutine 2 you might need to look at Y first then interpret A in the context of Y, etc. So probably a hook function is the way to go, maybe with a default hook subroutine that can interpret a dictionary of some form for where that's good enough.

I'd envision the hook function taking the CPU state and returning a text description (e.g. "sprite number") and/or a constant name (e.g. "sprite_peanut") for each registers. We'd then use the constant name if available and if we have an immediate operand to expr() or a non-immediate load to inline comment, otherwise we'd fall back to inline comments with the text description.

Arguably the text description is not needed, because that's provided as part of the subroutine() call (e.g. entry_a), but for more complex subroutines we might want to vary the text string on a per-call basis because the value in one of the registers changes what values in another register means. For example, if A=1 on entry, X is "file handle" and if A=2 on entry, X="operation subcode".

I hope this makes sense, I'm just thinking out loud really. It may well be that if the subroutine changes its behaviour based on one of the registers it's just considered too complex to handle via the subroutine() mechanism and the user has to handle it manually via code like that in acorn.py for the OS subroutine decoding.

**Comment by TobyLobster** [comment]
< thinking out loud >Yeah, I agree a hook function is useful here. 

1. From the ground up, a generic:

    find_instruction(instruction, hook_function)

could be used at least internally to share the 'find instruction' technology as needed. 

2. Perhaps a version that would find any call to a subroutine would be useful:

    find_subroutine_calls(subroutine_label_or_addr, hook_function)

which would find JSR subroutine, JMP subroutine, BMI subroutine, etc.

3. The hook function would be passed the current address and CPUState object.

4. I'm thinking the CPUState class should be beefed up, to allow for different searches we can see needing, e.g.:

```
    state.get_previous_load_imm('a')       # previous LDA # instruction, if not overwritten later
    state.get_previous_adjust('a')         # previous time A was adjusted or loaded.
    state.get_next_use('a')                # next time a is used, if not overwritten first.
```
This would allow tests like this:

    if state.has_previous_load_immediate('a'):
        valueA, addrA = state.get_previous_load_immediate('a')
        expr(addrA, osfile_index[valueA])
    elif state.has_previous_adjust('a'):
        valueA, addrA = state.get_previous_adjust('a')
        comment(addrA, "A=OSFILE parameter")

Having done all the logic it seems natural for the hook function to call expr() or comment() or both or whatever else it needs as it sees fit.

Where does subroutine() fit in all this? Maybe the subroutine parameter data is passed to the hook function as well if present. Then the hook function can use that information if it's useful.

< /thinking out loud >

**Comment by ZornsLemma** [comment]
That all looks pretty sensible to me.

I like the find_subroutine_calls() version, I hadn't thought that for the program's own subroutines (as opposed to the standard OS calls) you can enter via instructions like BMI. On that note, although it's a corner case, ideally we'd also recognise falling through into the first instruction of the subroutine as an implicit call if possible - this might be messy as there is no "call" instruction, but since the instructions we're interested in labelling are not the actual JMP/JSR/BMI/... instructions but the preceding loads, it would probably not be a big deal.

I think you're right about the subroutine() data being made available to the hook function, either as an argument or just via accessing the data structure subroutine() is adding to. To follow on from your example, the string "A=OSFILE parammeter" could potentially be retrieved from the subroutine() data. It might also be helpful to allow the osfile_index dictionary  to be associated with A via a subroutine() call as well. Obviously all of this is very speculative and we might want to start off with something simple then add things like this later.

**Comment by TobyLobster** [comment]
That sounds right. I hadn't thought of the fall through case - this should be easy to include. The MOS itself does a lot of that to save space.
